# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 07:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('titlt', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 15, 7, 27, 45, 4417, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('publish',),
            },
        ),
    ]
