# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_article',
            name='publish',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 15, 7, 40, 15, 137306, tzinfo=utc)),
        ),
    ]
