# Generated by Django 2.1.2 on 2018-10-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskarticle', '0002_auto_20181024_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='category',
        ),
    ]
